<?php require APP_PATH . '/views/layouts/header.php'; ?>
<style>
.payment-layout{display:grid;grid-template-columns:1fr 300px;gap:24px;max-width:970px}
.payment-card{background:#fff;border-radius:18px;padding:32px;box-shadow:var(--shadow)}
.payment-card-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:17px}
.payment-card h2{font-size:32px;margin-bottom:8px}
.payment-total{display:flex;justify-content:space-between;align-items:center;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:20px 0;margin:28px 0 22px}
.payment-total span{color:var(--muted);font-size:13px}.payment-total strong{font:700 25px "Space Grotesk"}
.payment-info,.payment-success,.payment-error{display:flex;gap:11px;align-items:flex-start;border-radius:10px;padding:14px;margin-bottom:17px;font-size:12px}
.payment-info{background:#f1f7dd}.payment-info>span{font-size:18px}.payment-info p,.payment-success p,.payment-error p{margin:0;color:var(--muted);line-height:1.55}
.payment-success{background:#e8f8c5}.payment-success>span{font-size:20px;color:#5f8100}.payment-success strong,.payment-error strong{display:block;margin-bottom:3px}
.payment-error{background:#ffe3dc;color:#a23e2d}.payment-hint{color:var(--muted);font-size:11px;text-align:center;margin:14px 0 0}
.side-note{background:var(--dark);color:#fff;border-radius:16px;padding:25px;margin-bottom:18px}.side-note .eyebrow{color:var(--lime);margin-bottom:17px}
.payment-step{display:flex;gap:12px;padding:15px 0;border-top:1px solid #ffffff2b}.payment-step b{font:700 11px "Space Grotesk";color:var(--lime)}
.payment-step p{font-size:12px;color:#c1c7c2;margin:0;line-height:1.45}.payment-side>.back-link{font-size:12px}
@media(max-width:700px){.payment-layout{grid-template-columns:1fr}.payment-card{padding:24px}.payment-side{order:-1}.payment-side .side-note{display:none}}
</style>
<section class="page-head compact"><div class="container page-head-inner"><div><div class="eyebrow">Secure checkout</div><h1>Bayar & <em>konfirmasi.</em></h1><p>Booking sudah tersimpan dan slot ditahan. Selesaikan pembayaran agar booking resmi terkonfirmasi.</p></div></div></section>
<section class="section section-light"><div class="container payment-layout"><div class="payment-main"><div class="payment-card"><div class="payment-card-top"><span class="overline">ORDER <?= e($payment['order_id'] ?? 'SWOOSH') ?></span><?php if ($paid): ?><span class="badge badge-success">Sudah dibayar</span><?php else: ?><span class="badge badge-warning">Menunggu pembayaran</span><?php endif; ?></div><h2><?= e($booking['field_name']) ?></h2><p class="muted">⌖ <?= e($booking['city']) ?> · <?= formatDateId($booking['booking_date']) ?> · <?= substr($booking['start_time'], 0, 5) ?>–<?= substr($booking['end_time'], 0, 5) ?></p><div class="payment-total"><span>Total pembayaran</span><strong><?= formatRupiah($booking['total_price']) ?></strong></div><?php if ($paid): ?><div class="payment-success"><span>✓</span><div><strong>Pembayaran diterima.</strong><p>Booking kamu sudah dikonfirmasi dan tersimpan di kalender.</p></div></div><a class="btn btn-dark btn-wide" href="<?= url('bookings') ?>">Lihat booking saya ↗</a><?php elseif (!empty($gatewayError)): ?><div class="payment-error"><strong>Pembayaran online belum siap.</strong><p><?= e($gatewayError) ?></p></div><a class="btn btn-ghost btn-wide" href="<?= url('payment/checkout', ['id' => $booking['id']]) ?>">Coba lagi</a><?php elseif ($isLive ?? false): ?><div class="payment-info"><span>↗</span><p>Kamu akan diarahkan ke halaman pembayaran Midtrans yang aman. Pilih metode pembayaran yang tersedia di sana.</p></div><a class="btn btn-primary btn-wide" href="<?= e($payment['redirect_url']) ?>" target="_blank" rel="noopener">Lanjut ke Midtrans ↗</a><p class="payment-hint">Setelah selesai, kembali ke halaman Booking saya. Status akan diperbarui otomatis oleh webhook Midtrans.</p><?php else: ?><form method="post" action="<?= url('payment/demo-complete') ?>"><input type="hidden" name="_csrf" value="<?= csrf_token() ?>"><input type="hidden" name="booking_id" value="<?= e($booking['id']) ?>"><button class="btn btn-primary btn-wide" type="submit">Simulasikan pembayaran berhasil ↗</button></form><?php endif; ?></div></div><aside class="payment-side"><div class="side-note"><span class="eyebrow">HOW IT WORKS</span><div class="payment-step"><b>01</b><p>Slot ditahan sementara untuk booking kamu.</p></div><div class="payment-step"><b>02</b><p>Selesaikan pembayaran sesuai total harga.</p></div><div class="payment-step"><b>03</b><p>Booking berubah menjadi terkonfirmasi.</p></div></div><a class="back-link" href="<?= url('bookings') ?>">← Kembali ke booking saya</a></aside></div></section>
<?php require APP_PATH . '/views/layouts/footer.php'; ?>